---
- name: ngnix_role
  src: https://github.com/Anandhcl3/ngnix_role.git
  scm: git
  version: main

- name: mysql_role
  src: https://github.com/Anandhcl3/mysql_role.git
  scm: git
  version: main

